### ISSUE TITLE
How to add embedded jetty server with this project?

### ISSUE THREAD

**Issue by ghost** [kristian/file-manager-servlet#3]
I want to run this project with embedded jetty server. 

I tried . But , failed.

How to add embedded jetty server with this project?

**Comment by kristian** [comment]
Hello @parasuraam, this project does not use any external dependencies and implements the servlet interface. Thus it should run on any servlet engine, including Jetty, e.g. following the attached example [1]. Without any detail about the problems you are facing, there is unfortunately no way to help you, thus I am going to be closing this issue.

[1] https://www.eclipse.org/jetty/documentation/current/embedded-examples.html#embedded-minimal-servlet

**Comment by poorvajappja** [comment]
How can I run this project?

**Comment by kristian** [comment]
Please see the example I linked above. Everything is explained there. Instead of adding the example Servlet simply run the servlet of this project.

**Comment by ghost** [comment]
How can I run this project?

When I run this project with tomcat server . it comes like this


![1](https://user-images.githubusercontent.com/67687893/89761075-4cedd680-db0b-11ea-8e6e-1825d44dc491.PNG)

I tried lot of times .but , all failed.

Can you give a solution for this?

**Comment by kristian** [comment]
You need to register the servlet to a path you want to access it to. Please see this [1] instruction on how to do so. This is NOT a help forum @parasuraam, thus I am going to be locking this thread now. In case you have a real issue with *my* project, please open another issue. Thanks.

[1] https://www.baeldung.com/register-servlet
